apiVersion: v1
kind: Service
metadata:
  name: hello-nodejs
  labels:
    app: hello
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello

